# -*- Mode: yaml -*-
#
# Playbook for updating
#
# remote user can vary (ubuntu, pi, or my own ID)
#
# To run:
#
#   env ANSIBLE_COW_SELECTION=random
#   env ANSIBLE_NOCOWS=1
#   ansible-playbook update-debian.yml -i hosts
#
# To verify:
#   ansible-lint update-debian.yml
#
# To encrypt / decrypt credentials:
#   ansible-vault [encrypt|decrypt] --vault-password-file=whatever init/foo.env
#

---
- hosts: debian
  become: yes
  become_method: sudo
  gather_facts: false

  tasks:
    # - include_tasks: tasks/debug.yml
    - include_tasks: tasks/apt_update.yml
    - include_tasks: tasks/apt_upgrade.yml
